# Generated by Django 5.2.7 on 2025-11-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
