# Generated by Django 5.2.7 on 2025-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_created_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_detail',
            field=models.TextField(default='', max_length=30),
        ),
    ]
