# Generated by Django 5.2.7 on 2025-11-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_detail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
