# Generated by Django 5.2.7 on 2025-11-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_detail',
            new_name='location',
        ),
    ]
