# Generated by Django 5.2.7 on 2025-11-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='created_by',
        ),
    ]
